version: "3.3"

services:
  mysql_service:
    image: mysql:8.0.21
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'zipster'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      container_network:

networks:
  container_network:
    driver: bridge