version: "3.8"

services:
  spark_service:
    image: howarddeiner/zipster-aws-on-demand-spark
    deploy:
      replicas: 2 # number of containers in total on mesh
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.function==spark-worker"
      update_config:
        parallelism: 1 # one container per node
      restart_policy:
        condition: on-failure
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    environment:
      VAULT_TOKEN: $VAULT_TOKEN
      VAULT_ADDRESS: $VAULT_ADDRESS
      ENVIRONMENT: $ENVIRONMENT
    networks:
      - overlay
#    healthcheck:
#      test:  "curl http://localhost:8080/zipster -d '{\"zipcode\":\"07440\",\"radius\":\"1.5\"}'"
#      interval: 1m30s
#      timeout: 10s
#      retries: 3

networks:
  overlay:
    driver: overlay
    attachable: true