version: "3.3"

services:
  spark_service:
    image: howarddeiner/zipster-aws-on-demand-spark
    container_name: spark_container
    ports:
      - "8080:8080"
    environment:
      VAULT_TOKEN: $VAULT_TOKEN
      VAULT_ADDRESS: $VAULT_ADDRESS
      ENVIRONMENT: $ENVIRONMENT
    networks:
      container_network:

networks:
  container_network:
    driver: bridge
